### ISSUE TITLE
🐛 [Bug] Minio does not implement filesystem.Driver

### ISSUE THREAD

**Issue by rymesaint** [goravel/goravel#393]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [X] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Windows

### Golang Version (Go 版本)

1.21.x

### Goravel Version (Goravel 版本)

1.13.8

### Describe The Problem (描述问题)

After upgrading to 1.13.8 the goravel/minio get an error like this "cannot use driver (variable of type *Minio) as filesystem.Driver value in return statement: *Minio does not implement filesystem.Driver (missing method GetBytes)"

**Comment by devhaozi** [comment]
try `go get -u github.com/goravel/minio`

**Comment by hwbrzzl** [comment]
Yes, upgrade goravel/minio to v1.1.2.
